### ISSUE TITLE
Plugin does not recognize service layer

### ISSUE THREAD

**Issue by kenhks** [awslabs/serverless-plugin-lambda-insights#27]
Version Info
Serverless: 3.18.1
Serverless-plugin-lambda-insights: 1.5.0

```yml
# serverless.yml
provider:
  name: aws
  ...
  layers:
    - layer1ARN

functions:
  func1:
    ...
   # no function level layer

plugins:
  - serverless-plugin-lambda-insights
```

Expected Outcome:
func1 has two layers, `layer1` and `LambdaInsightsExtension`

Actual Result:
func1 has only one layer  `LambdaInsightsExtension`

**Comment by nicemaker** [comment]
The issues above I managed to workaround by just adding the layer to each function, like:
```
functions:
  myFun:
    handler: src/serverless.myFun
    layers:
      - {MyLayerArn}
```
Would be great though to be able to be able to add my layer only on provider level and done.
And, very important, I think this issue also creates conflicts with other plugins, in my case `serverless-layers`, see config below, serverless layers doesn't really need any configuration. As soon as I remove lambda insights its working as expected:

```
plugins:
  modules:
    - serverless-plugin-lambda-insights
    - serverless-layers
    
    ....
custom:
  lambdaInsights:
     defaultLambdaInsights: true
```
