### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cyberfox1** [awslabs/serverless-plugin-lambda-insights#4]
1 validation error detected: Value 'arn:aws:lambda:${opt:region, self:custom.region}:580247275435:layer:LambdaInsightsExtension:14' at 'arn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+

**Comment by cstanger** [comment]
Hey @cyberfox1, 
thank you for pointing that out.

Can you confirm that your serverless yaml looks similar to that:

```yaml
provider:
  name: aws
  region: ${opt:region, self:custom.defaultRegion}
```
It seems like the Serverless variable expression does not get resolved properly during plugin execution.
