### ISSUE TITLE
enhanced monitoring has warning

### ISSUE THREAD

**Issue by lodewaelbers** [awslabs/serverless-plugin-lambda-insights#40]
I have enabled lambda insights in my project with serverless:

npm install --save-dev serverless-plugin-lambda-insights =>     "serverless-plugin-lambda-insights": "^2.0.0",

```
custom:
  lambdaInsights:
    defaultLambdaInsights: true #enables Lambda Insights for all functions
[...]
plugins:
  - serverless-plugin-lambda-insights
```

When I deploy, enhanced monitoring is active but there is a warning on monitoring and operations:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/80754013/233345180-1048873b-2506-4304-8993-fb5805843b3b.png">

Looking for more detail brings me to
<img width="971" alt="image" src="https://user-images.githubusercontent.com/80754013/233345319-db72396c-0816-481c-8b10-b1dd5e1bb00d.png">

The execution role has no denies. The CloudWatchLambdaInsightsExecutionRolePolicy is added.

I have the same effect on multiple lambda functions.

How can I deploy without running into a warning?
