### ISSUE TITLE
Cannot read property 'defineFunctionProperties' of undefined when deploy

### ISSUE THREAD

**Issue by baby3873575** [awslabs/serverless-plugin-lambda-insights#6]
# Bug Report

## Description
SLS deploy throws error when using lambda-insights

#### What did you do?
```
sls deploy --verbose -s dev
```
#### What happened?

TypeError: Cannot read property 'defineFunctionProperties' of undefined

#### What should've happened?
should deploy successfully

#### What's the content of your serverless.yml file?

```
service: mysvc #change service name will be different deployment
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    certificateArn:
      prod: ---
      dev: ---
      test: ---
  

  customDomain:
    domainName: ${opt:stage, self:provider.stage}.---.com
    stage: ${opt:stage, self:provider.stage}
    # basePath: 'v1'
    endpointType: 'regional'
    createRoute53Record: true
    region: ap-northeast-1
    certificateArn: ${self:custom.domains.certificateArn.${opt:stage, self:provider.stage}}
    serverless-offline:
      noPrependStageInUrl: true
  lambdaInsights:
    defaultLambdaInsights: false

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-step-functions
  - serverless-offline
  - serverless-plugin-lambda-insights

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - venv/**

provider:
  name: aws
  stage: ${opt:stage, dev}
  runtime: python3.7
  region: ap-northeast-1
  RoleName: "${self:service}-${self:provider.stage}-serverless-role"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "*"

    - Effect: "Allow"
      Action:
        - "cognito-idp:AdminInitiateAuth"
      Resource: "arn:aws:cognito-idp:${opt:region, self:provider.region}:*:*"

functions:
  wf:
    name: ${self:service}-${self:provider.stage}-wf
    handler: mybot.handler
    lambdaInsights: true
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          path: /api/msg/send
          method: post
          cors: true

resources:
  Resources:
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        AliasAttributes:
          - email
          - phone_number
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: OFF
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True

    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-user-pool-client
        GenerateSecret: False
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_CUSTOM_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        UserPoolId:
          Ref: CognitoUserPool

    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: ${self:service}-${self:provider.stage}-cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: 
          Ref: 'ApiGatewayRestApi'

    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
          
```

#### What's the output you get when you use the SLS_DEBUG=* environment variable (e.g. SLS_DEBUG=* serverless deploy)

```
sls deploy --verbose -s dev
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command invoke
Serverless: Load command invoke:stepf
Serverless: Load command offline
Serverless: Load command offline:start
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'defineFunctionProperties' of undefined
      at new AddLambdaInsights (/somepath/node_modules/serverless-plugin-lambda-insights/index.js:28:36)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:78:28)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:115:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:115:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:96:35
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:94:8)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:79:4)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.1
     Framework Version:         1.72.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.14
     
 ```
